/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.3/userguide/building_swift_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}

rootProject.name = "alumnihub"
include("app")
include("domain")
include("commons:ktorm")
include("commons:test")
include("commons:util")
include("framework")
include("starter:ktorm-spring-boot-starter")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            library("ktorm-core", "org.ktorm:ktorm-core:3.6.0")
            library("ktorm-mysql", "org.ktorm:ktorm-support-mysql:3.6.0")
            library("ktorm-postgresql", "org.ktorm:ktorm-support-postgresql:3.6.0")
            library("ktorm-jackson", "org.ktorm:ktorm-jackson:3.6.0")

            // spring boot
            library("spring-boot-starter", "org.springframework.boot", "spring-boot-starter").withoutVersion()
            library("spring-boot-web-starter", "org.springframework.boot", "spring-boot-starter-web").withoutVersion()
            library("spring-boot-jdbc-starter", "org.springframework.boot", "spring-boot-starter-data-jdbc").withoutVersion()
            library("spring-boot-test-starter", "org.springframework.boot", "spring-boot-starter-test").withoutVersion()
            library("jackson-kotlin", "com.fasterxml.jackson.module", "jackson-module-kotlin").withoutVersion()

            // test
            library("mockk", "io.mockk", "mockk").version("1.13.8")
            library("spring-mockk", "com.ninja-squad", "springmockk").version("4.0.2")

            // database
            library("h2", "com.h2database", "h2").withoutVersion()
            library("postgresql", "org.postgresql", "postgresql").withoutVersion()
        }
        create("project") {
            library("ktorm-starter", project(":starter:ktorm-spring-boot-starter").toString())
        }
    }
}
