spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.ktorm: debug
    org.springframework.security: trace

security:
  key: whatever_whatever_whatever_whatever
  validity: 7200 # 单位秒, 两个小时
