spring:
  datasource:
    username: alumnihub
    password: alumnihub@123
    url: jdbc:postgresql://49.235.108.166:5432/alumnihub
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.ktorm: debug
    org.springframework.security: trace

security:
  key: whatever_whatever_whatever_whatever
  validity: 7200 # 单位秒, 两个小时
axon:
  axonserver:
    enabled: false