spring:
  datasource:
    username: alumnihub
    password: alumnihub@123
    url: jdbc:postgresql://49.235.108.166:5432/alumnihub
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org.ktorm: debug
#    org.springframework.security: trace

security:
  key: whatever_whatever_whatever_whatever
  validity: 604800 # 单位秒, 7天
axon:
  axonserver:
    enabled: false

alumnihub:
  qiniu:
    access_key: s4SPEO65jbQcaYETip7cdGah3WjAiriKvjM7ucXt
    secret_key: 6MC03xfL7ugL-wNV5sSJv-6kiAj3E3arZwwpsI81
    bucket: alumnihub-zj
    domain: sc1i8ek9f.hd-bkt.clouddn.com
