spring:
  datasource:
    password: alumnihub
    username: alumnihub
    url: jdbc:postgresql://localhost:5432/alumnihub
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.ktorm: debug
