spring:
  datasource:
    password: alumnihub
    username: alumnihub
    url: jdbc:postgresql://localhost:5432/alumnihub
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.ktorm: debug
    org.springframework.security: trace

security:
  key: whatever_whatever_whatever_whatever
  validity: 7200 # 单位秒, 两个小时
