
/*
 * This file was generated by the Gradle 'init' task.
 */
val kotlinxSerialization by project.properties

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("io.github.qumn.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}


dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:${kotlinxSerialization}")
}