/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("io.github.qumn.kotlin-common-conventions")

    id("org.springframework.boot")
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
}
