/*
 * This file was generated by the Gradle 'init' task.
 */

val kotlinVersion = "1.9.0"

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
    implementation("org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin:${kotlinVersion}")
    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.1.4")
    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.1.4")
    implementation("io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.3")
}
